/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f7f1ff',
        'on-tertiary-fixed-variant': '#7e2c00',
        'error': '#ba1a1a',
        'on-primary-container': '#e3dbff',
        'inverse-primary': '#c9bfff',
        'tertiary-container': '#ac4000',
        'quaternary-green': '#4CD964',
        'outline-variant': '#c9c3da',
        'primary': '#4900e5',
        'on-primary-fixed-variant': '#4500d8',
        'surface-container-highest': '#e5e0f0',
        'on-surface-variant': '#484456',
        'on-secondary-fixed-variant': '#900b1b',
        'error-container': '#ffdad6',
        'primary-container': '#6236ff',
        'background': '#fdf8ff',
        'on-secondary-fixed': '#410005',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe6060',
        'secondary': '#b2292f',
        'text-muted': '#7F7F8A',
        'on-background': '#1c1a25',
        'outline': '#797488',
        'surface-dim': '#ddd8e7',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f4eefe',
        'inverse-surface': '#312f3a',
        'tertiary-yellow': '#FFC043',
        'surface-variant': '#e5e0f0',
        'text-main': '#1C1C1E',
        'tertiary-fixed': '#ffdbcd',
        'on-error': '#ffffff',
        'surface-bright': '#fdf8ff',
        'on-primary': '#ffffff',
        'on-secondary-container': '#65000d',
        'on-tertiary-fixed': '#360f00',
        'surface-container-high': '#ebe6f5',
        'on-tertiary': '#ffffff',
        'tertiary': '#852f00',
        'surface-card': '#FFFFFF',
        'surface': '#fdf8ff',
        'secondary-fixed': '#ffdad7',
        'on-primary-fixed': '#1b0063',
        'tertiary-fixed-dim': '#ffb597',
        'primary-fixed': '#e5deff',
        'on-surface': '#1c1a25',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#c9bfff',
        'on-tertiary-container': '#ffd8c9',
        'background-canvas': '#F4F5F7',
        'surface-container': '#f1ebfb',
        'secondary-fixed-dim': '#ffb3af',
        'surface-tint': '#5d2ffa',
      },
      spacing: {
        'card-padding': '24px',
        'container-margin': '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-md-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'heading-md': ['1.25rem', { fontWeight: '600' }],
        'body-base': ['1rem', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['0.813rem', { lineHeight: '18px', fontWeight: '500' }],
      },
      borderRadius: {
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
